[package]
name = "random-chains"
version = "0.1.0"
authors = ["Davide Mancusi <davide.mancusi@cea.fr>"]
edition = "2018"

[dependencies]
clap = ">= 2.33.0"
rand = ">= 0.7.3"
rand_distr = ">= 0.2.2"
GSL = "1.1"

[dev-dependencies]
assert_float_eq = ">= 1.1.3"
